[package]
name = "boring-example"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
boring = "2"

[patch.crates-io]
boring-sys = { path = "../boring/boring-sys" }
